version: '2.4'
volumes:
  scd30-data:
services:
  scd30:
    build:
      context: .
    restart: always
    network_mode: host
    volumes:
      - scd30-data:/usr/src/app
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
